query HelpArticleQuery($article: String!) {
  cms {
    faq(id: $article) {
      sys {
        id
        publishedAt
      }
      title
      program {
        name
        webname
      }
      audience
      answer {
        json
        links {
          assets {
            block {
              sys {
                id
              }
              contentType
              url
            }
          }
        }
      }
      relatedAnswers {
        items {
          sys {
            id
          }
          title
        }
      }
    }
  }
}

query HelpArticlePathsQuery {
  cms {
    faqs (limit: 1000) {
      items {
        sys {
          id
        }
      }
    }
  }
}
