query EduProgramsQuery {
  cms {
    eduPrograms: programs {
      items {
        name
        webname
        shortDescription
        logo {
          url
        }
        educationDetails {
          json
        }
      }
    }
  }
}
