packages:
  - apps/*
  - packages/*
allowBuilds:
  core-js: true
  ejs: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
catalog:
  "@chakra-ui/react": "^3.34.0"
  "@emotion/react": "^11"
  "@emotion/styled": "^11"
  "@types/node": "^25.5.0"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  eslint: "^8.35.0"
  graphql: "^16.0.1"
  next: "16.0.10"
  "@wrksz/themes": "^0.1.0"
  prop-types: "^15.7.2"
  react: "^19.0.0"
  react-dom: "^19.0.0"
  typescript: "^6.0.2"
