query HelpProgramAudienceQuery ($programWebname: String!, $audience: String!) {
  cms {
    programs(where: { webname: $programWebname }, limit: 1) {
      items {
        name
      }
    }
    events(where: { program: { webname: $programWebname } }, limit: 15) {
      items {
        linkedFrom {
          pressPhotos(limit: 1) {
            items {
              photo {
                url(transform: {width: 1024, height: 250, resizeStrategy: FILL, quality: 80})
              }
            }
          }
        }
      }
    }
    faqs (where: { program: { webname: $programWebname }, audience_contains_all: [$audience] }, order: [featured_DESC]) {
      items {
        title
        tags
        answer {
          json
        }
        sys {
          id
        }
      }
    }
  }
}

query HelpProgramAudiencePathsQuery {
  cms {
    programs (limit: 100) {
      items {
        webname
        linkedFrom {
          faqs {
            items {
              audience
            }
          }
        }
      }
    }
  }
}
