query ListFormsQuery {
  cms {
    forms {
      items {
        slug
      }
    }
  }
}

query FormQuery($slug: String) {
  cms {
    forms(where: { slug: $slug }, limit: 1) {
      items {
        title
        cognitoForm
        slug
        image {
          url(transform: { width: 1000, height: 300, resizeStrategy: CROP})
        }
        details {
          json
          links {
            assets {
              block {
                sys {
                  id
                }
                contentType
                url
              }
            }
          }
        }
        sidebar {
          json
          links {
            assets {
              block {
                sys {
                  id
                }
                contentType
                url
              }
            }
          }
        }
      }
    }
  }
}
