fragment IndexQuotesComponent on Query {
  cms {
    quoteTestimonials: testimonials(where: { featured: true }) {
      items {
        quote
        firstName
        lastName
        groupName
        title
        company
        experience
        type
        image {
          url(transform: {width: 32, height: 32})
        }
        largeImage: image {
          url(transform: {width: 300, height: 150})
        }
        video {
          url
        }
        program {
          name
        }
        region {
          name
          webname
          location {
            lat
            lon
          }
        }
      }
    }

    quoteRegions: regions {
      items {
        webname
        name
        location {
          lat
          lon
        }
      }
    }
  }
}
