fragment VolunteerPhotoGallery on Query {
  cms {
    volunteerPhotoGallery: pressPhotos ( where: { tags_contains_some: ["volunteer"] } ) {
      items {
        photo { url( transform: { width: 600, height: 400, resizeStrategy: FILL } )}
        region { name }
        event {
          title
          program { name }
        }
      }
    }
  }
}
