fragment VolunteerProgramInfoComponent on Query {
  cms {
    volunteerPrograms: programs (limit: 15) {
      items {
        name
        webname
        logo {
          url
        }
        virtual
        volunteerUrl
        volunteerDetails {
          json
        }
        volunteerBlurb {
          json
        }
        volunteerRecruitingResources (limit: 10) {
          items {
            title
            contentType
            url
            preview: url(transform: { width:100, height:100, resizeStrategy:FILL })
          }
        }
        type
        volunteerPositions
        linkedFrom {
          events (limit: 100) {
            items {
              startsAt
              endsAt
            }
          }
        }
      }
    }
  }
}
