fragment VolunteerTestimonials on Query {
  cms {
    volunteerTestimonials: testimonials(where: { image_exists: true, featured: true }, limit: 10) {
      items {
        quote
        firstName
        lastName
        experience
        title
        company
        type
        program { name }
        image {
          url(transform: { resizeStrategy: FILL, width: 64, height: 64 })
        }
      }
    }
  }
}
