query ContactQuery {
  account {
    employees: roleUsers (roleId: "rol_llN0357VXrEoIxoj") {
      id
      username
      name
      title
      picture
      bio
      pronoun
    }

    otherTeam: roleUsers (roleId: "rol_6t902YZpsOynmWDt") {
      id
      username
      name
      title
      picture
      bio
      pronoun
    }

    contractors: roleUsers (roleId: "rol_kQxfFcpISf1SyqPw") {
      id
      username
      name
      title
      picture
      bio
      pronoun
    }

    board: roleUsers (roleId: "rol_cU5c8wlFVbSh6I2w") {
      id
      username
      givenName
      familyName
      title
      picture
      bio
      pronoun
    }

    volunteers: roleUsers (roleId: "rol_Z10C6Hfr4bfqYa4r") {
      id
      username
      name
      title
      picture
    }

    emeritus: roleUsers (roleId: "rol_H5SU2E05hXd2m9pJ") {
      id
      username
      name
      picture
    }
  }

  cms {
    email: strings (where: { key: "contact.public.email" }, limit: 1) {
      items {
        value
      }
    }

    phone: strings (where: { key: "contact.public.phone" }, limit: 1) {
      items {
        value
      }
    }

    address: strings (where: { key: "contact.public.address" }, limit: 1) {
      items {
        value
      }
    }
  }
}
