query ContactQuery {
  account {
    employees: roleUsers (roleId: "rol_llN0357VXrEoIxoj") {
      id
      name
      title
      picture
      bio
      pronoun
    }

    board: roleUsers (roleId: "rol_cU5c8wlFVbSh6I2w") {
      id
      givenName
      familyName
      title
      picture
      bio
      pronoun
    }

    volunteers: roleUsers (roleId: "rol_Z10C6Hfr4bfqYa4r") {
      id
      name
      title
      picture
    }
  }

  cms {
    email: strings (where: { key: "contact.public.email" }, limit: 1) {
      items {
        value
      }
    }

    phone: strings (where: { key: "contact.public.phone" }, limit: 1) {
      items {
        value
      }
    }

    address: strings (where: { key: "contact.public.address" }, limit: 1) {
      items {
        value
      }
    }
  }
}
