query ListPublicationsQuery {
  cms {
    publications (where: { type: "dataset" }) {
      items {
        title
        doiSuffix
        publicationDate
        license
        contributors {
          name
          affiliation
        }
      }
    }
  }
}
