query DocsQuery {
  cms {
    legalDocuments(order:[type_ASC, date_DESC], limit:1000) {
      items {
        title
        type
        file {
          contentfulBaseUrl
        }
      }
    }
  }
}
