#import "../components/Page.gql"
#import "../components/Index/Hero.gql"
#import "../components/Index/Stats.gql"
#import "../components/Index/Programs.gql"
#import "../components/Index/Sponsors.gql"
#import "../components/Index/Announcement.gql"
#import "../components/Index/Community.gql"
#import "../components/Index/Quotes/index.gql"
#import "../components/Index/EcoBox.gql"
#import "../components/Index/Workshops.gql"
query IndexQuery ($cmsDate: CmsDateTime, $calendarDateStart: CalendarDateTime!, $calendarDateEnd: CalendarDateTime!) {
  ...PageComponent
  ...IndexHeroComponent
  ...IndexStatsComponent
  ...IndexProgramsComponent
  ...IndexSponsorsComponent
  ...IndexAnnouncementComponent
  ...IndexCommunityComponent
  ...IndexQuotesComponent
  ...IndexEcoBoxComponent
  ...IndexWorkshopsComponent
}
