#import "../components/Page.gql"
#import "../components/Index/Hero.gql"
#import "../components/Index/Stats.gql"
#import "../components/Index/Programs.gql"
#import "../components/Index/Sponsors.gql"
#import "../components/Index/Announcement.gql"
#import "../components/Index/Community.gql"
#import "../components/Index/Quotes/index.gql"
query IndexQuery ($cmsDate: CmsDateTime) {
  ...PageComponent
  ...IndexHeroComponent
  ...IndexStatsComponent
  ...IndexProgramsComponent
  ...IndexSponsorsComponent
  ...IndexAnnouncementComponent
  ...IndexCommunityComponent
  ...IndexQuotesComponent


  cms {
    eco: strings(where: { key: "eco.blurb" }, limit: 1) {
      items {
        value
      }
    }

    learnMore: strings(where: { key: "common.learn-more" }, limit: 1) {
      items {
        value
      }
    }
  }
}
