#import "../components/Press/PhotoGallery.gql"
#import "../components/PreviousCoverageLogos.gql"

query PressQuery {
  ...PressPhotoGalleryComponent
  ...PreviousCoverageLogosComponent
  cms {
    mission: strings (where: { key: "common.mission" }, limit: 1) {
      items {
        value
      }
    }

    pressDetails: strings (where: { key: "press.details" }, limit: 1) {
      items {
        richValue {
          json
        }
      }
    }

    pressContact: strings (where: { key: "press.contact" }, limit: 1) {
      items {
        richValue {
          json
        }
      }
    }

    programs(where: {type:"primary"}) {
      items {
        logo {
          url
        }
        name
        shortDescription
      }
    }
  }
}
