#import "../components/Press/PhotoGallery.gql"
#import "../components/PreviousCoverageLogos.gql"

query PressQuery {
  ...PressPhotoGalleryComponent
  ...PreviousCoverageLogosComponent
  cms {
    mission: strings (where: { key: "common.mission" }, limit: 1) {
      items {
        value
      }
    }

    pressDetails: strings (where: { key: "press.details" }, limit: 1) {
      items {
        richValue {
          json
        }
      }
    }

    pressContact: strings (where: { key: "press.contact" }, limit: 1) {
      items {
        richValue {
          json
        }
      }
    }


    previousCoverage: newsCoverages (order: date_DESC, limit: 12) {
      items {
        title
        date
        publicationName
        url
      }
    }

    programs(where: { type:"primary", archived_not: true }) {
      items {
        logo {
          url
        }
        name
        shortDescription
      }
    }
  }
}
