#import "../components/VideoTestimonialThumbnail.gql"
#import "../components/Volunteer/ProgramInfo.gql"

query VolunteerQuery {
  ...VolunteerProgramInfoComponent
  cms {
    testimonials: testimonials(where: { featured: true, type_in:["Volunteer", "Mentor"] }) {
      items {
        ...VideoTestimonialThumbnailComponent
        firstName
        lastName
        title
        company
      }
    }
  }
}
