query VolunteerQuery {
  cms {
    volunteerPrograms: programs {
      items {
        name
        logo {
          url
        }
        virtual
        volunteerUrl
        volunteerDetails {
          json
        }
        type
        volunteerPositions
        linkedFrom {
          events (limit: 100) {
            items {
              startsAt
              endsAt
            }
          }
        }
      }
    }
  }
}
