query ApplyAsVolunteerQuery($webname: String!) {
  clear {
    findFirstEvent(where: { contentfulWebname: { equals: $webname } }, orderBy: { startDate: desc }) {
      managers
    }
  }
  cms {
    regions(where: { webname: $webname }) {
      items {
        newVolunteerPipeline
      }
    } 
  }
}