fragment PageComponent on Query {
  cms {
    mission: strings (where: { key: "common.mission" }) {
      items {
        value
      }
    }

    globalSponsors (where: { legalDisclaimer_exists: true }) {
      items {
        legalDisclaimer
      }
    }
  }
}
