fragment PreviousCoverageLogosComponent on Query {
  cms {
    coverageLogos: newsCoverages (where: { featured: true }, order: date_DESC, limit: 20) {
      items {
        publicationName,
        publicationLogo {
          url(transform: {width: 200})
        }
        url
      }
    }
  }
}
