fragment PressPhotoComponent on CmsPressPhoto {
  tags
  photo {
    title
    description
    original: contentfulBaseUrl
    preview: url(transform: { width: 400, height: 250, resizeStrategy: FILL })
  }
  event {
    startsAt
    program {
      name
    }
  }
  subProgram {
    name
  }
  region {
    name
  }
}
