query HelpProgramIndexQuery ($programWebname: String!) {
  cms {
    programs(where: { webname: $programWebname }, limit: 1) {
      items {
        name
      }
    }
    events(where: { program: { webname: $programWebname } }, limit: 15) {
      items {
        linkedFrom {
          pressPhotos(limit: 1) {
            items {
              photo {
                url(transform: {width: 1024, height: 250, resizeStrategy: FILL, quality: 80})
              }
            }
          }
        }
      }
    }
    faqs(where: { program: {webname: $programWebname } }, limit: 1000) {
      items {
        audience
      }
    }
  }
}

query HelpProgramIndexPathsQuery {
  cms {
    programs {
    	items {
        webname
        linkedFrom {
          faqs(limit: 1) {
            items {
              sys {
                id
              }
            }
          }
        }
      }
    }
  }
}
