query LegalPathsQuery {
  notion {
    pages(parentSlug: "legal") {
      slug
    }
  }
}

query LegalContentQuery($slug: String!, $parentSlug: String!) {
  notion {
    page(slug: $slug, parentSlug: $parentSlug) {
      title
      slug
      content
    }
  }
}

query TermageddonLegalContentQuery {
  termageddon {
    terms(locale: "en-US") {
      disclaimer
      tos
      cookies: cookiePolicy
      privacy: privacyPolicy
    }
  }
}
