fragment IndexAnnouncementComponent on Query {
  announcementWebinar: calendar {
    events(after: $calendarDateStart, before: $calendarDateEnd, calendars: ["webinars"]) {
      id
      title
      calendarId
      calendarName
      start
      end
      metadata
      location
    }
  }
  cms {
    announcements(
      where: { visibility: "Public", displayAt_lte: $cmsDate, endAt_gte: $cmsDate }
    ) {

      items {
        sys {
          id
        }
        title
        oneline
        displayAt
        type
        link
        displayAt
        programs {
          items {
            webname
          }
        }
      }
    }
  }
}
