fragment IndexCommunityComponent on Query {
  showYourWork {
    messages(take:50) {
      text
      imageUrl(width: 300, height: 300, strategy: CROP)
      author {
        name
        picture(transform: { width: 32, height: 32, fit: CROP})
      }
    }
  }

  showcase {
    projects( where:{media: IMAGES}) {
      id
      name
      media {
        type
        topic
        image(width: 300, height: 300, strategy: CROP)
      }
      members {
        account {
          name
          picture(transform: { width: 32, height: 32, fit:CROP })
        }
      }
    }
  }

  cms {
    indexCommunityPhotos: pressPhotos(limit: 100) {
      items {
        region {
          name
        }
        event {
          program {
            name
          }
          startsAt
        }
        photo {
          url(transform: { width: 300, height: 300, format: JPG_PROGRESSIVE, resizeStrategy: FILL })
        }
      }
    }
  }
}
