query GetMyLocation{
  geo {
    mine {
      lat
      lng
    }
  }
}

fragment IndexProgramsComponent on Query {
  clear {
    events (where: { endDate: { gte: $clearDate } }) {
      name
      contentfulWebname
      registrationsOpen
    }
  }
  cms {
    codeDayProgram: programs(where: { name:"CodeDay" }) {
      items {
        shortDescription
        linkedFrom {
          events (limit: 100) {
            items {
              startsAt
              endsAt
            }
          }
        }
      }
    }

    mainPrograms: programs(where: { name_not:"CodeDay", type:"primary", archived_not: true }) {
      items {
        name
        url
        shortDescription
        logo {
          url
        }
        linkedFrom {
          events (limit: 100) {
            items {
              startsAt
              endsAt
            }
          }
        }
      }
    }

    otherPrograms: programs(where: { name_not:"CodeDay", type_not:"primary", archived_not: true }) {
      items {
        name
        url
        shortDescription
        logo {
          url
        }
      }
    }

    regions (limit: 500) {
      items {
        name
        webname
        location {
          lat
          lon
        }
      }
    }
  }
}
