fragment IndexProgramsComponent on Query {
  cms {
    codeDayProgram: programs(where: { name:"CodeDay" }) {
      items {
        shortDescription
        linkedFrom {
          events (limit: 100) {
            items {
              startsAt
              endsAt
            }
          }
        }
      }
    }

    mainPrograms: programs(where: { name_not:"CodeDay", type:"primary" }) {
      items {
        name
        url
        shortDescription
        logo {
          url
        }
        linkedFrom {
          events (limit: 100) {
            items {
              startsAt
              endsAt
            }
          }
        }
      }
    }

    otherPrograms: programs(where: { name_not:"CodeDay", type_not:"primary" }) {
      items {
        name
        url
        shortDescription
        logo {
          url
        }
      }
    }

    regions (limit: 500) {
      items {
        name
        webname
        location {
          lat
          lon
        }
      }
    }
  }
}
