fragment IndexSponsorsComponent on Query {
  cms {
    majorSponsors: globalSponsors(where: { type: "major" }, order: [sys_firstPublishedAt_ASC]) {
      items {
        name
        link
        type
        logo {
          url(transform: {height: 160, width: 320, resizeStrategy: PAD})
        }
        darkLogo {
          url(transform: {height: 160, width: 320, resizeStrategy: PAD})
        }
      }
    }

    minorSponsors: globalSponsors(where: { type: "minor" }, order: [sys_firstPublishedAt_ASC]) {
      items {
        name
        link
        type
        logo {
          url(transform: {height: 80, width: 160, resizeStrategy: PAD})
        }
        darkLogo {
          url(transform: {height: 80, width: 160, resizeStrategy: PAD})
        }
      }
    }
  }
}
