#import "../PreviousCoverageLogos.gql"
fragment IndexStatsComponent on Query {
  ...PreviousCoverageLogosComponent
  cms {
    stats: events (limit:500) {
      items {
        statEventCount
        statStudentCount
        statLowInterestCount
        statLowInterestContinuedCount
      }
    }
  }

  labs {
    statTotalOutcomes {
      key
      value
    }
  }
}
