fragment IndexStatsComponent on Query {
  cms {
    stats: events (limit:500) {
      items {
        statEventCount
        statStudentCount
        statLowInterestCount
        statLowInterestContinuedCount
      }
    }
  }
}
