fragment IndexWorkshopsComponent on Query {
  calendar {
    events(after: $calendarDateStart, before: $calendarDateEnd) {
      id
      title
      calendarId
      calendarName
      location
      start
      description
      metadata
    }
  }
}
