fragment EventInfo on CalendarCalendarEvent {
  title
  description
  location
  metadata
  calendarId
  calendarName
  start
  end
  subscriberCount
}


mutation SubscribeToEvent($calendarId: String!, $id: String!, $destination: String!) {
  calendar {
    subscribe(calendarId: $calendarId, eventId: $id, destination: $destination)
  }
}
