query HelpIndexQuery {
  cms {
    programs(where: { archived_not: true }) {
      items {
        name
        webname
        shortDescription
        logo {
          url(transform: { width: 300, height: 100 })
        }
        linkedFrom {
          faqs(limit: 1) {
            items {
              sys {
                id
              }
            }
          }
        }
      }
    }
  }
}
