query ListPublicationsQuery {
  cms {
    publications {
      items {
        doiSuffix
      }
    }
  }
}

query PublicationQuery($doiSuffix: String) {
  cms {
    publications(where: { doiSuffix: $doiSuffix }, limit: 1) {
      items {
        title
        description
        doiSuffix
        type
        publicationDate
        license
        funderName
        funderIdentifier
        contributors {
          username
          name
          orcid
          affiliation
          givenName
          familyName
        }
        files {
        	items {
            title
            fileName
            contentfulBaseUrl
          }
        }
      }
    }
  }
}
